### ISSUE TITLE
On BC19 - not compatible

### ISSUE THREAD

**Issue by szenzi** [wbrakowski/Record-Deletion-Tool#2]
Hi!
I really love your solution, but on the BC 19 the app is not compatible.
Could you check it please why not?
Thanks a lot!

**Comment by wbrakowski** [comment]
@szenzi Hey szenzi. Thank you for reporting this, I haven't used this app in a while. I will check what the problem is and keep you posted.

**Comment by wbrakowski** [comment]
@szenzi It should work with BC 19 now. Thanks for your report and have fun. 👍

**Comment by szenzi** [comment]
> @szenzi It should work with BC 19 now. Thanks for your report and have fun. 👍

Really thx U!!!! :)
