### ISSUE TITLE
Extension validation failed - Error AL0132 and PTE0004

### ISSUE THREAD

**Issue by hkusulja** [wbrakowski/Record-Deletion-Tool#5]
Hello,
I have downloaded your .app and tried to install to latest Dynamics 365 Business Central - SaaS - v20.3.
I have SUPER permission set assigned.

> Uploading Extension: 'Record-Deletion-Tool' by 'Waldemar Brakowski'.

> Extension validation failed. View the error details for more information.

> Package validation failed due to the following error(s): src/codeunit/RecordDeletionMgt.Codeunit.al (554,35) - Error AL0132: 'Database' does not contain a definition for 'Delivery Reminder Header'
> src/codeunit/RecordDeletionMgt.Codeunit.al (554,89) - Error AL0132: 'Database' does not contain a definition for 'Phys. Invt. Diff. List Buffer'
> src/table/RecordDeletion.Table.al (1,13) - Error PTE0004: Table '50000' is missing a matching permission set.
> src/table/RecordDeletionRelError.Table.al (1,13) - Error PTE0004: Table '50001' is missing a matching permission set. - Job Id : 357c6025-2064-42ec-9b9c-58365230327a

**Comment by BorisTheBug** [comment]
Hello @hkusulja Thanks for reporting, I will have a look at it.

**Comment by wbrakowski** [comment]
Hello @hkusulja Thanks for reporting, I will have a look at it.

**Comment by wbrakowski** [comment]
@hkusulja Should be fixed now. Feel free to reopen if something does not work as expected. 
Thanks again and have a nice day.

**Comment by hkusulja** [comment]
@wbrakowski 
Thank you so much for the fix.
I tried to test, however it seems for me that you have removed .app file from your releases on GitHub.
Currently I am unable to compile the .app (but it is my issue), can you maybe please also publish the .app file in git repo and/or github releases? Thank you in advance

**Comment by wbrakowski** [comment]
I added it again.

**Comment by hkusulja** [comment]
Thank you, it works, Kind regards!
