### ISSUE TITLE
No. Of Records - Filter Issue - BC On Prem 

### ISSUE THREAD

**Issue by Adil-d365bc** [wbrakowski/Record-Deletion-Tool#8]
Hey,

I have deployed the extension on Business Central 21 - On Prem. After Insert - Update Tables action the records are populated with No. of Records on each Table. 

Problem: When applying Filter as 
No. Of Records <> 0 , to just check tables which has records.  It is showing metadata 0 error something. 
Below is the piece of code attached. 

field(20; "No. of Records"; Integer)
        {
            Caption = 'No. of Records';
            Editable = false;
            FieldClass = FlowField;
            //CalcFormula = lookup ("Table Information"."No. of Records" where("Company Name" = field(Company), "Table No." = field("Table ID")));
            //CalcFormula = lookup ("Table Information"."No. of Records" where("Company Name" = field(Company), "Table No." = field("Table ID")));
        }

I used this tool in earlier NAV versions and it worked fine and the CalCFormula works well there. However in BC there is some restriction to use "Table Information" Table in Lookup. 

Can you please check and let us know about it.

**Comment by wbrakowski** [comment]
Hello @Adil-d365bc 
The restriction to use "Table Information" only applies to SaaS/Cloud. I have not found a way to enable the filter for SaaS/Cloud environments.

However, as you said that you deployed the extension on Business Central 21 - OnPrem, you can make this work with small changes:

1. Open the app.json and change the target from "Cloud" to "OnPrem"

![image](https://user-images.githubusercontent.com/53928639/221136917-7fa9e6b8-5510-41cc-a34e-63e447886934.png)



2. Set the CalcFormula for field "No. of Records"

![image](https://user-images.githubusercontent.com/53928639/221136841-811d7bcf-d314-4d82-a48e-44551fccbfce.png)

3. Change the field "NoOfRecords" in the page "Record Deletion", it should look like this:

![image](https://user-images.githubusercontent.com/53928639/221137131-6cc5b6f2-ed46-452a-832f-b77373b50f18.png)

Hope this helps. :-)
