### ISSUE TITLE
Doesn't work with BC25

### ISSUE THREAD

**Issue by sebsid** [wbrakowski/Record-Deletion-Tool#9]
Package validation failed due to the following error(s): src/codeunit/RecordDeletionMgt.Codeunit.al (3,29) - Error AL0806: The object ID '17' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,227) - Error AL0806: The object ID '110' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,250) - Error AL0806: The object ID '111' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,273) - Error AL0806: The object ID '112' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,296) - Error AL0806: The object ID '113' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,319) - Error AL0806: The object ID '114' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,342) - Error AL0806: The object ID '115' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,365) - Error AL0806: The object ID '120' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,388) - Error AL0806: The object ID '121' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,411) - Error AL0806: The object ID '122' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,434) - Error AL0806: The object ID '123' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,51) - Error AL0806: The object ID '36' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,457) - Error AL0806: The object ID '124' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,480) - Error AL0806: The object ID '125' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,503) - Error AL0806: The object ID '169' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,526) - Error AL0806: The object ID '379' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,549) - Error AL0806: The object ID '380' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,572) - Error AL0806: The object ID '271' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,595) - Error AL0806: The object ID '5802' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,619) - Error AL0806: The object ID '6650' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,643) - Error AL0806: The object ID '6660' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (135,37) - Error AL0433: Table 'Intrastat Jnl. Line' is removed. Reason: Intrastat related functionalities are moved to Intrastat extensions.. Tag: 25.0.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,73) - Error AL0806: The object ID '37' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,95) - Error AL0806: The object ID '38' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,117) - Error AL0806: The object ID '39' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,139) - Error AL0806: The object ID '81' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,161) - Error AL0806: The object ID '21' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,183) - Error AL0806: The object ID '25' should not be surrounded with quotes.
src/codeunit/RecordDeletionMgt.Codeunit.al (3,205) - Error AL0806: The object ID '32' should not be surrounded with quotes. - Job Id : 2a5e108b-7fb5-4700-9b39-6560c25f04dd

**Comment by szenzi** [comment]
Thx sebsid, I like to ask the same yes, but haven't got enough time yet.

**Comment by wbrakowski** [comment]
@sebsid Thank you for reporting, I will have a look at this in approx. 2 weeks.

**Comment by wbrakowski** [comment]
@sebsid  @szenzi 7
Should be fixed now. Thank you!
